### PR TITLE
Added local Storage to Preserve the selected Company

### PR DESCRIPTION
**Pull request by nitin094-hub**
I have added local storage to Preserve the options that were checked by the user. So whenever he/she revisit the web app, the companies that the user checked earlier will be preserved. Issue : #18

### CODE REVIEW

**Comment by Priyaraj17** [comment]
Hey, will take a look at it soon :)

**Review by Priyaraj17 — APPROVED** [review]
Looks good.

**Comment by nitin094-hub** [comment]
I am glad to contribute If there is any other relevant issue for me.

**Comment by Priyaraj17** [comment]
Yeah sure. Thanks 😊

**Pull request merged**
